replicaCount: 2

image:
  repository: nanajanashia/argocd-app:1.0
  tag: 1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi